In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

## Reading the data

In [2]:
df = pd.read_csv('voice.csv')
df.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [4]:
 df.shape

(3168, 21)

In [5]:
df.columns

Index(['meanfreq', 'sd', 'median', 'Q25', 'Q75', 'IQR', 'skew', 'kurt',
       'sp.ent', 'sfm', 'mode', 'centroid', 'meanfun', 'minfun', 'maxfun',
       'meandom', 'mindom', 'maxdom', 'dfrange', 'modindx', 'label'],
      dtype='object')

In [6]:
df.describe

<bound method NDFrame.describe of       meanfreq        sd    median       Q25       Q75       IQR       skew  \
0     0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1     0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2     0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3     0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4     0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   
...        ...       ...       ...       ...       ...       ...        ...   
3163  0.131884  0.084734  0.153707  0.049285  0.201144  0.151859   1.762129   
3164  0.116221  0.089221  0.076758  0.042718  0.204911  0.162193   0.693730   
3165  0.142056  0.095798  0.183731  0.033424  0.224360  0.190936   1.876502   
3166  0.143659  0.090628  0.184976  0.043508  0.219943  0.176435   1.591065   
3167  0.165509  0.092884  0.183044  0.070072  0.250827  0.180756   1.705029   

             kurt

In [7]:
print("Total number of labels: {}".format(df.shape[0]))
print("Number of male: {}".format(df[df.label == 'male'].shape[0]))
print("Number of female: {}".format(df[df.label == 'female'].shape[0]))

Total number of labels: 3168
Number of male: 1584
Number of female: 1584


In [13]:
df.drop(['centroid'], axis=1, inplace=True)

In [14]:
df.drop(['dfrange'], axis=1, inplace=True)

In [15]:
df.columns

Index(['meanfreq', 'sd', 'median', 'Q25', 'Q75', 'IQR', 'skew', 'kurt',
       'sp.ent', 'sfm', 'mode', 'meanfun', 'minfun', 'maxfun', 'meandom',
       'mindom', 'maxdom', 'modindx', 'label'],
      dtype='object')

In [16]:
Male_df = X.loc[df.label == "male"]
Female_df = X.loc[df.label == "female"]
print(Male_df.shape)
print(Female_df.shape)

(1584, 18)
(1584, 18)


## Defining X and Y values 

In [18]:
X = df.loc[:,df.columns != 'label']
X.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm      mode   meanfun    minfun    maxfun  \
0   274.402906  0.893369  0.491918  0.000000  0.084279  0.015702  0.275862   
1   634.613855  0.892193  0.513724  0.000000  0.107937  0.015826  0.250000   
2  1024.927705  0.846389  0.478905  0.000000  0.098706  0.015656  0.271186   
3     4.177296  0.963322  0.727232  0.083878  0.088965  0.017798  0.250000   
4     4.333713  0.971955  0.783568  0.104261  0.106398  0.016931  0.266667   

    meandom    mindom    maxdom   modindx  
0  0.007812  0.007812  0.007812  0.000000  
1  0.009014  0.007812  0.054688  0.052632  
2  0.007990  0.007812  0.015625  0.046512  
3  0.201497  0.007812  0.562500  0.247119  
4  0.712812  0.007812  5.484375  0.208274

In [19]:
drop_cols=[]
for cols in X.columns:
    if X[cols].std()==0:
        drop_cols.append(cols)
print("Number of constant columns to be dropped: ", len(drop_cols))
print(drop_cols)
X.drop(drop_cols,axis=1, inplace = True)

Number of constant columns to be dropped:  0
[]


C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [20]:
Y = df.loc[:,df.columns == 'label']
Y.head()

label
0  male
1  male
2  male
3  male
4  male

## Label Encoding 

In [21]:
from sklearn.preprocessing import LabelEncoder
gender_encoder = LabelEncoder()
Y = gender_encoder.fit_transform(Y)
Y

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([1, 1, 1, ..., 0, 0, 0])

## Data Standardisation 

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

## Splitting dataset into training set and testing set for better generalisation 

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2 , random_state = 1)

In [25]:
X_train

array([[ 1.86207010e+00, -1.71596009e-01,  1.76797458e+00, ...,
        -7.08404312e-01,  2.10497090e-03,  2.38645483e-01],
       [-1.66398788e-01,  6.06764772e-01, -2.58218587e-01, ...,
        -7.08404312e-01,  2.70613827e-01,  1.11204756e-01],
       [ 8.75265120e-01, -1.02179942e+00,  7.67376592e-01, ...,
         2.13073231e+00, -1.37697161e-01,  4.19888377e-01],
       ...,
       [ 4.25197419e-01,  9.12515119e-02,  7.55436212e-01, ...,
        -4.61522866e-01,  2.37327605e-01, -1.99812508e-01],
       [-1.30836832e+00,  1.16448382e+00, -1.81602035e+00, ...,
        -7.08404312e-01, -1.38925910e+00,  1.99713759e+00],
       [ 4.56609368e-01,  3.54136977e-02,  8.80430493e-01, ...,
        -4.61522866e-01,  9.76281728e-01, -3.77184091e-01]])

## Default Linear kernel

In [39]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear')
classifier.fit(X_train,Y_train)
Y_pred=classifier.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(Y_test,Y_pred)
accuracy = float(cm.diagonal().sum())/len(Y_test)
print("\nAccuracy : ", accuracy)


Accuracy :  0.9779179810725552


In [40]:
cm

array([[305,   6],
       [  8, 315]], dtype=int64)

## Default RBF kernel

In [45]:
svc=SVC(kernel='rbf')
svc.fit(X_train,Y_train)
Y_pred=svc.predict(X_test)
con= confusion_matrix(Y_test,Y_pred)
accuracy = float(con.diagonal().sum())/len(Y_test)
print('Accuracy Score:',accuracy )

Accuracy Score: 0.9779179810725552


In [46]:
con

array([[305,   6],
       [  8, 315]], dtype=int64)

## Default Polynomial kerne

In [47]:
svc=SVC(kernel='poly')
svc.fit(X_train,Y_train)
Y_pred=svc.predict(X_test)
c= confusion_matrix(Y_test,Y_pred)
accuracy = float(c.diagonal().sum())/len(Y_test)
print('Accuracy Score:',accuracy )

Accuracy Score: 0.9652996845425867


In [48]:
c

array([[294,  17],
       [  5, 318]], dtype=int64)

In [51]:
print("Precision:",confusion_matrix.accuracy_score(y_test, y_pred))
print("Recall:",confusion_matrix(y_test, y_pred))

AttributeError: 'function' object has no attribute 'accuracy_score'